In [1]:
import numpy as np 

In [2]:
a = [2, 4, 5, 6]
b = [4, 5, 6, 6]
a + b 

[2, 4, 5, 6, 4, 5, 6, 6]

In [15]:
d = dict([(("A{}".format(x), x**2), x) for x in range(10)])

In [16]:
d 

{('A0', 0): 0,
 ('A1', 1): 1,
 ('A2', 4): 2,
 ('A3', 9): 3,
 ('A4', 16): 4,
 ('A5', 25): 5,
 ('A6', 36): 6,
 ('A7', 49): 7,
 ('A8', 64): 8,
 ('A9', 81): 9}

In [18]:
for (x, y), v in d.items():
    print(x, y, v)

A0 0 0
A1 1 1
A2 4 2
A3 9 3
A4 16 4
A5 25 5
A6 36 6
A7 49 7
A8 64 8
A9 81 9


In [11]:
(z, k) = 10, 8

In [21]:
class A:
    def __init__(self, *args, **kwargs):
        self.name = 'Mario'

In [22]:
p = A()

In [2]:
import numpy as np 

In [3]:
state = np.random.random(size=(4,))

In [4]:
state 

array([0.8346806 , 0.77544764, 0.80277617, 0.18273868])

In [27]:
m = np.random.random(size=(4, 6))

In [38]:
m + np.random.normal(loc=0, scale=.01, size=m.shape)

array([[0.38912479, 0.9764597 , 0.29581343, 0.85146041, 0.13694731,
        0.96085256],
       [0.69568566, 0.91562706, 0.02687847, 0.33023799, 0.2004795 ,
        0.75325578],
       [0.24094734, 0.70004353, 0.27032337, 0.65821102, 0.27778569,
        0.74040128],
       [0.30047642, 0.59897954, 0.67453881, 0.29526248, 0.44182788,
        0.26548485]])

In [31]:
softmax(m.T.dot(state))

array([0.11046846, 0.31411317, 0.06691287, 0.17076142, 0.06306859,
       0.27467548])

In [5]:
actions = np.random.random(size=(6,))

In [23]:

print(actions)
# softmax
softmax = lambda x: np.exp(x) / sum(np.exp(x))


print(np.exp(actions) / sum(np.exp(actions)))
p = actions / np.sum(actions)
np.random.choice(range(len(actions)), p=p)

[0.7452081  0.91538262 0.16953023 0.56825984 0.41603618 0.40110868]
[0.19944013 0.23643861 0.11214988 0.16709555 0.14350102 0.14137482]


3

In [25]:
print(np.argmax([.4, .5, .1]))
print(softmax([.4, .5, .1]))

print(np.argmax([.1, .8, .1]))
print(softmax([.1, .8, .1]))


1
[0.35137169 0.38832577 0.26030255]
1
[0.2491434 0.5017132 0.2491434]
